import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=""
      >
        <Header />
        {children}
        <footer className="flex justify-center items-center h-12 bg-gray-200">
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
