import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Nexus",
  description: "Generated by create next app",
  icons: {
    icon: "/test.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className="min-h-screen flex flex-col relative">
        <Header />
        <main className="flex flex-col row-start-2 items-center pb-32  relative bg-white">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}

// px-8 sm:px-12 md:px-16 xl:px-[8%] 2xl:px-[15%]
