import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { Inter } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Nexus",
  description: "Generated by create next app",
  icons: {
    icon: "/test.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body
        className=""
      >
        <Header />
        {children}
        <footer className="flex justify-center items-center h-12 bg-gray-200">
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
